
  
SNOWFLAKE_USER:
  account:account
  user: user
  password: password
  role: role
  warehouse: warehouse
  database: database
  schema: schema
  use_openssl_only: false
  ocsp_fail_open: false



  

  







