# .streamlit/secrets.toml

[connections.snowpark]
account = "ar16523.ap-south-1.aws"
user = "dhanush_poc"
password = "Dhanushp@1"
role = "POC_DEVELOPER"
warehouse = "STREAMLIT_WH"
database = "POC_DB"
schema = "POC_SCHEMA"
client_session_keep_alive = true
